### ISSUE TITLE
Error: ENAMETOOLONG: name too long

### ISSUE THREAD

**Issue by supperdsj** [weidian-inc/hera#10]
文件将生成到:
/Users/dongsj/WebstormProjects/demo/heraDemo/heraDemo/heraTmp/web
发生了未知错误

Error: ENAMETOOLONG: name too long, mkdir '/Users/dongsj/WebstormProjects/demo/heraDemo/heraDemo/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web/heraTmp/web'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.exports.mkdirsSync (/Users/dongsj/.nvm/versions/node/v8.9.1/lib/node_modules/hera-cli/node_modules/weweb-cli/lib/util.js:290:10)
    at Object.exports.copyDir (/Users/dongsj/.nvm/versions/node/v8.9.1/lib/node_modules/hera-cli/node_modules/weweb-cli/lib/util.js:338:10)
    at /Users/dongsj/.nvm/versions/node/v8.9.1/lib/node_modules/hera-cli/node_modules/weweb-cli/lib/util.js:358:16
    at Array.forEach (<anonymous>)
    at Object.exports.copyDir (/Users/dongsj/.nvm/versions/node/v8.9.1/lib/node_modules/hera-cli/node_modules/weweb-cli/lib/util.js:339:11)
    at /Users/dongsj/.nvm/versions/node/v8.9.1/lib/node_modules/hera-cli/node_modules/weweb-cli/lib/util.js:358:16
    at Array.forEach (<anonymous>)
    at Object.exports.copyDir (/Users/dongsj/.nvm/versions/node/v8.9.1/lib/node_modules/hera-cli/node_modules/weweb-cli/lib/util.js:339:11)
    at /Users/dongsj/.nvm/versions/node/v8.9.1/lib/node_modules/hera-cli/node_modules/weweb-cli/lib/util.js:358:16%

**Comment by IOriens** [comment]
您好，请尝试删除`/Users/dongsj/WebstormProjects/demo/heraDemo/`和`/Users/dongsj/WebstormProjects/demo/heraDemo/heraDemo/`目录下的`heraTmp`文件夹

然后在`/Users/dongsj/WebstormProjects/demo/heraDemo/`目录下执行 `hera run web`

**Comment by supperdsj** [comment]
这很诡异。。。在上一级目录下执行就不会出错了

**Comment by IOriens** [comment]
目前是不可以在小程序代码所在的目录执行 hera run 命令的。

因为最终需要将小程序代码打成 zip 包发布出去，我们不能把客户端代码和 tmp 文件夹放置小程序代码所在的目录，采取两层目录的形式实属无奈 ┑(￣Д ￣)┍
