### ISSUE TITLE
通过 hera 命令转换后的其他平台代码，怎样入手修改？

### ISSUE THREAD

**Issue by AbooJan** [weidian-inc/hera#11]
比如通过 `hera run web` ，会生成一个web项目；`hera run ios` 会生成一个iOS工程，生成的网页会在资源压缩包里。

看了转换成成 web 或者是 iOS的代码，里面的 `html` 或者是 `js` 文件都是经过压缩、变量处理的。

如果有问题要修改，该怎样入手呢？
又或者想针对 `web \ ios` 做特殊处理，又该怎样入手修改呢？

**Comment by pgfxm** [comment]
转换后的代码我们是不建议改的，在小程序源码里进行平台区分处理就可以了，怎么去区分不同平台这块我们很快会把文档补全起来：）
