### ISSUE TITLE
The initialization running error in Windows7

### ISSUE THREAD

**Issue by harrydengchao** [weidian-inc/hera#12]
### description: 
- init project, running error in Windows7

### system
- Windows 7 [64bit]
- node version is v7.10.1
- npm version is 4.0.5
- hera version is 1.2.1
- node version manager tool is [nodist](https://github.com/marcelklehr/nodist)
- use global node version

---

### operation history:

![image](https://user-images.githubusercontent.com/13941171/33197586-63b40d90-d121-11e7-8f5f-5a1798dccbdb.png)

---

Thank you.

**Comment by IOriens** [comment]
There is a blank space in the path to where hera-cli was installed.
![image](https://user-images.githubusercontent.com/8137136/33201870-4011e4c0-d135-11e7-802d-9258a7f91d39.png)

You can try to execute the following command with the path quoted by the single quotation mark.
![image](https://user-images.githubusercontent.com/8137136/33201979-afa3fbac-d135-11e7-8739-19a5a3bf8718.png)
Like this:
```
node 'c:\Program FIles\node\......'  simple -b -d heraTmp/web
```
It would be great if you can tell us whether it works, it seems that we should quote the executable command's path all the time.

**Comment by IOriens** [comment]
We've fixed this problem and published it to npm. You can use following command to upgrade your cli and try it again, thanks for your feedback.
```sh
npm i -g hera-cli
```

**Comment by harrydengchao** [comment]
updated hera-cli to 1.2.3

---

Executing. As a failure
![image](https://user-images.githubusercontent.com/13941171/33248416-d44de7e8-d35f-11e7-9075-ef4ed9b85101.png)

---

It seems to be a path problem, indicating the "Cannot find module 'C:\ Program'.
![image](https://user-images.githubusercontent.com/13941171/33248383-a186b60a-d35f-11e7-98da-f283b9186c04.png)

**Comment by IOriens** [comment]
Just solved this problem, you can install beta version to try it, this is cause by nodist, it installs global modules in a weird path. I solved it by stringify all the absolute path used in our project.

```sh
npm i -g hera-cli@beta
```

**Comment by IOriens** [comment]
We've fixed this problem and published it to npm. You can use the following command to upgrade your cli and try it again, thanks for your feedback.
```sh
npm i -g hera-cli
```

**Comment by harrydengchao** [comment]
fixed. nice
