### ISSUE TITLE
win10下运行Web报错

### ISSUE THREAD

**Issue by 673800357** [weidian-inc/hera#13]
![2](https://user-images.githubusercontent.com/20512530/33208078-1d220164-d14b-11e7-8aec-941a1e0b65b4.png)

**Comment by IOriens** [comment]
老哥不用 close，我改上一个 bug 改出问题了，现在回退了

**Comment by 673800357** [comment]
@IOriens 好嘞，现在直接用就可以了是吧？

**Comment by IOriens** [comment]
更新完直接运行`hera run web`就行了
