### ISSUE TITLE
iOS 下获取 getImageInfo 失败

### ISSUE THREAD

**Issue by liwangqiang** [weidian-inc/hera#14]
在 WHE_getImageInfo.m 中
```
...
NSString *fileName = fileURL.lastPathComponent;
...
```
如果fileURL的格式是： `wdfile://tmp_123456789.jpg`, 则 fileURL.lastPathComponet 为 nil， tmp_123456789.jpg 被识别为了host。导致image取不到。

如果给url加一个斜杠，如 wdfile://tmp_123456789.jpg => wdfile:///tmp_123456789.jpg
代码逻辑就没问题了，可以获取正常。但是 image 控件识别不了这个url，不能显示出来了。

**Comment by liwangqiang** [comment]
or 
if ([self.src hasPrefix:@"wdfile://tmp_"]) {
        fileName = [[self.src componentsSeparatedByString:@"//"] lastObject];
}

**Comment by wwwyiqiao** [comment]
ok 已经修复了
