### ISSUE TITLE
wxss中background为url()时  //被过滤为空格

### ISSUE THREAD

**Issue by Yi-Frank** [weidian-inc/hera#16]
wxss中background为url()时  //被过滤为空格...双斜杠被过滤成空格了...
试了一下如果加成"\\/\\/"会变成出一个/

**Comment by Yi-Frank** [comment]
file = file.replace(/^\.?\//, '')

这个是在weweb/lib/wxss.js   line 21  找到的  
不知道能不能帮上忙

**Comment by Yi-Frank** [comment]
尝试着注释掉一部分代码...好像可以了...但是不知道这里是不是有其他作用...

hera-cli\node_modules\weweb-cli\node_modules\wxss-transpiler\index.js   line 46

const cssSource = getContent(initFile)      //.replace(/\/\//g, ' ')

注释掉了.replace    
大神可否告知一下这里的作用是什么?

**Comment by IOriens** [comment]
之前是因为要把 css 放置到单行，所以不能用`//`做为注释，我们用正则把它转换成空格了。现在不需要放置到单行了，所以注释掉`.replace`也可以跑。

我们回头改下哈，之前没想到你这种情况。

**Comment by Yi-Frank** [comment]
嗯嗯嗯  晓得啦...谢谢大神
