### ISSUE TITLE
基于wepy的小程序的转换问题

### ISSUE THREAD

**Issue by vicky625** [weidian-inc/hera#17]
小程序是基于wepy开发的，编译后将dist目录复制到hera项目的dist后，执行hera run web，编译正常，但是访问报错，错误如下所示。
weweb.js?v=1.0.4:1 TypeError: Cannot set property 'Promise' of undefined
    at app-service.js?v=1.0.4:1767
    at s (weweb.js?v=1.0.4:1)
    at weweb.js?v=1.0.4:1
    at app-service.js?v=1.0.4:4665
    at s (weweb.js?v=1.0.4:1)
    at app-service.js?v=1.0.4:4672
window.onerror @ weweb.js?v=1.0.4:1

weweb.js?v=1.0.4:1 TypeError: Cannot read property '$pages' of undefined
    at Object.$createPage (app-service.js?v=1.0.4:1897)
    at eval (my.js:60)
    at s (weweb.js?v=1.0.4:1)
    at eval (my.js:61)
    at weweb.js?v=1.0.4:1
    at <anonymous>

**Comment by liwangqiang** [comment]
信息太少，undefined 指的哪个变量，如果是 wd，那可能是转换wx->wd，出了点问题。仅供参考。

**Comment by IOriens** [comment]
Fixed at [fix: Promise in app](https://github.com/wdfe/weweb/commit/efcdd788d411d6ad1eae0833dbd0674a13aa9817)
