### ISSUE TITLE
滑动返回的两个问题：滑动不流畅，干扰下拉刷新

### ISSUE THREAD

**Issue by wsxyeah** [weidian-inc/hera#25]
1. `ACTION_MOVE` 只对滑动距离大于一定值的时候做处理（`Math.abs(dx)>mTouchSlop`）导致滑动不流畅，断断续续。

    https://github.com/weidian-inc/hera/blob/f2ce7c754e3d32f05349980621b8374d7ca327eb/android/hera/src/main/java/com/weidian/lib/hera/page/view/PageWebView.java#L94

2.  `ACTION_UP` 直接调用了 `SwipeRefreshLayout.setEnable(true)`，导致下拉刷新的配置被覆盖，会强制开启下拉刷新。

    https://github.com/weidian-inc/hera/blob/f2ce7c754e3d32f05349980621b8374d7ca327eb/android/hera/src/main/java/com/weidian/lib/hera/page/view/PageWebView.java#L111

**Comment by lpw14** [comment]
master-dev分支已修复
