### ISSUE TITLE
mpvue生成的小程序转换不了，在微信开发工具可以正常预览

### ISSUE THREAD

**Issue by gordanyang** [weidian-inc/hera#39]
[demo.zip](https://github.com/weidian-inc/hera/files/2317293/demo.zip)

看上去像是mpvue增加的page的handleproxy方法没有invoke

[Log] parsePage {data: {__webviewId__: 106102872732432}, onLoad: function, onReady: function, …} (service.html, line 18)
[Log] TypeError: undefined is not an object (evaluating 'this[fn].apply') — service.js:5612 (service.html, line 18)
[Log] page event (service.html, line 18)
[Log] {eventName: "handleProxy", data: Object} (service.html, line 18)
[Log] function () { (service.html, line 18)
      try {
        return fn.apply(fn, arguments);
      } catch (e) {
        console.log(e);
        self.errorReport(e, extend);
        return function () {};
      }
    }
[Log] {data: Object, eventName: "handleProxy", webviewId: 106102872732432} (service.html, line 18)
[Info] Invoke event handleProxy in page: pages/counter/main (service.html, line 18)
[Log] parsePage {data: {__webviewId__: 106102872732432}, onLoad: function, onReady: function, …} (service.html, line 18)
[Log] TypeError: undefined is not an object (evaluating 'this[fn].apply') — service.js:5612 (service.html, line 18)

**Comment by gordanyang** [comment]
![image](https://user-images.githubusercontent.com/4629246/44614233-7ac0ae80-a853-11e8-9652-217e85c3a038.png)
![image](https://user-images.githubusercontent.com/4629246/44614243-962bb980-a853-11e8-898c-a26563bf263d.png)
![image](https://user-images.githubusercontent.com/4629246/44614250-9e83f480-a853-11e8-95ee-e814bf347bac.png)

**Comment by gordanyang** [comment]
已解决，是mpvue的bug

**Comment by ZYCZ-BaiWenLong** [comment]
可以问一下是怎么转换的吗

**Comment by gordanyang** [comment]
mpvue编译成小程序->再通过hera编译->再打开
