### ISSUE TITLE
非常棒的项目啊！ 目前hera还不支持window下的开发?

### ISSUE THREAD

**Issue by hunnad** [weidian-inc/hera#4]
执行hera run web时失败，
这句失败， weweb没有对应的weweb.cmd版本？
C:\Users\Administrator\AppData\Roaming\npm\node_modules\hera-cli\node_modules\weweb-cli\bin\weweb test -d heraTmp/web

**Comment by IOriens** [comment]
Windows 版本已经开发完成并发布到 npm 当中了，由于还处于测试阶段所以没有在文档中标注，您可以使用`npm i hera-cli -g` 命令更新脚手架来参与测试，(´⌣`ʃƪ)，感谢您的支持。

**Comment by hunnad** [comment]
棒，可以运行了。
