### ISSUE TITLE
字符实体&nbsp无法被解析

### ISSUE THREAD

**Issue by whatsbug** [weidian-inc/hera#5]
小程序text标签里面的&nbsp，在iOS模拟器直接显示“&nbsp”字符串

**Comment by pgfxm** [comment]
小程序本来就不&nbsp这种标签呀

**Comment by coco163** [comment]
在text里面 decode=“true”的情况下是可以解析
https://mp.weixin.qq.com/debug/wxadoc/dev/component/text.html

**Comment by pgfxm** [comment]
哦，这个特性目前还没支持呢，后续我们支持一下

**Comment by IOriens** [comment]
We've fixed this problem and published it to npm. You can use the following command to upgrade your cli and try it again, thanks for your feedback.
```sh
npm i -g hera-cli
```

**Comment by xiaomizhou66** [comment]
> 哦，这个特性目前还没支持呢，后续我们支持一下

官网文档不是可以的么？
https://developers.weixin.qq.com/miniprogram/dev/component/text.html

加上属性就ok了
Tips
decode可以解析的有 &nbsp; &lt; &gt; &amp; &apos; &ensp; &emsp;
各个操作系统的空格标准并不一致。
<text> 组件内只支持 <text> 嵌套。
除了文本节点以外的其他节点都无法长按选中。
