### ISSUE TITLE
关于web端的bug

### ISSUE THREAD

**Issue by coco163** [weidian-inc/hera#6]
非常不错的框架，不过web端还是有bug，比如底部导航栏超过4个点击错位。picker组件无法滚动。在chrome及firefox最新版测试都有问题。但是总体来说还是非常不错的，如果能加上路由过渡效果就更完美了

**Comment by pgfxm** [comment]
我们在chrome里测试底部导航栏超过4个点击是没有问题的，firefox没有做测试，毕竟小程序基本是面向移动端的。picker这个组件我们这看也是正常的。你是在chrome打开模拟手机模式下测试的么？因为用到touch事件，需要模拟手机打开

**Comment by pgfxm** [comment]
路由过渡效果就得后继再优化了，如果方便的话可以把你的demo发来看看

**Comment by coco163** [comment]
不好意思，我发现是我代码有问题，而且没有在模拟手机模式下打开。非常抱歉.....另外我想请问一下，如果要使用微信jssdk，是否需要在打包之后的代码进行二次开发？

**Comment by pgfxm** [comment]
嗯，有可能，那得看你具体想实现什么功能

**Comment by coco163** [comment]
比如实现微信支付或者读取用户信息，这些小程序有现成的api，但是打包成web或者app就没有这些api了

**Comment by pgfxm** [comment]
嗯，你可以进行二次开发，修改一下对应的api，你们实现后，也欢迎贡献一下你们这块的代码到项目里来：）

**Comment by pgfxm** [comment]
对了，web这块的源码可以看https://github.com/wdfe/weweb这个项目，这里是调用这个项目来实现的

**Comment by coco163** [comment]
好的，谢谢O(∩_∩)O
