### ISSUE TITLE
How to package into apk?

### ISSUE THREAD

**Issue by FengHaiSheng** [weidian-inc/hera#7]
like title!

**Comment by lpw14** [comment]
In the terminal to file folder 'hera/android/sample', and execute '../gradlew clean installDebug', you'll find the apk in the file folder 'build/outputs/apk'

**Comment by FengHaiSheng** [comment]
thanks! It's work.
If I use "hera-cli", I can find the apk in the file folder 'heraPlatforms/android/app/build/outputs/apk'.
