### ISSUE TITLE
ios 下运行，不支持右滑返回手势

### ISSUE THREAD

**Issue by AbooJan** [weidian-inc/hera#8]
iOS下运行，没有右滑返回，感觉好不方便。

iOS下应该挺好实现，我看iOS下的页面结构，是有NavigationController的

**Comment by AbooJan** [comment]
项目很酷，刚好需要用到这样一个框架，希望能不断更新完善

**Comment by wwwyiqiao** [comment]
是的 现在已经fix了 还没push上去
